### ISSUE TITLE
Light Suppression

### ISSUE THREAD

**Issue by DrossVoss** [ForwarD-NerN/NotSoShadowExtras#1]
Hi, i been checking both of your mods notsoshadowextras and antishadowpatch and i cant figure out how to get my light updtaes suppressed (when chunks stop loading)

**Comment by ForwarD-NerN** [comment]
Hello. NotSoShadowExtras currently doesn't have this functionality. There is "disableDataFixerLightRecalculation", but it's for converting pre-1.20 worlds to 1.20 without breaking EOL farms/already suppressed light.
This functionality actually exists in Carpet-TIS, so I don't think I need to add it.

**Comment by DrossVoss** [comment]
all right, do you have any discord server or your discord to keep in touch with you

**Comment by ForwarD-NerN** [comment]
Yes, my Discord username is outofmemoryerror
