### ISSUE TITLE
can i create an EOL farm using the mod like i have the mod installed on the server so can i make a light suppressor in 1.20.1? for EOL farm?

### ISSUE THREAD

**Issue by Mint169** [ForwarD-NerN/NotSoShadowExtras#2]
can i create an EOL farm using the mod like i have the mod installed on the server so can i make a light suppressor in 1.20.1? for EOL farm?

**Comment by ForwarD-NerN** [comment]
Answered in https://github.com/ForwarD-NerN/AntiShadowPatch/issues/7
