### ISSUE TITLE
Update Suppression Crash Fix consumes a lot of server power

### ISSUE THREAD

**Issue by Warp159** [ForwarD-NerN/NotSoShadowExtras#3]
![image](https://github.com/user-attachments/assets/93bd453b-9011-42e6-948c-18be399d8b0b)

**Comment by ForwarD-NerN** [comment]
It's not actually NSSE that uses this much power, it's the vanilla tickWorlds() method. For the crash fix to function, exceptions that occur during world ticking need to be caught. For that, I wrapped the tickWorlds() method and added a custom exception handling logic. 
If you expand it, then you would see the vanilla methods being called, and they're the ones that use 92%
